# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 09 Jun 2016 21:10:46 +0000
*	@ALL	0
*	@estudiante	1
*	@docente	8
user:%USER%:*	%USER%	16
user:%USER%	%USER%	2
user:*	@ALL	0
