<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: crawis
 * Date: Tue, 28 Jun 2016 00:06:48 +0200
 */

$conf['title'] = 'Wiki UBB';
$conf['start'] = 'bienvenido';
$conf['lang'] = 'es';
$conf['template'] = 'bootstrap3';
$conf['tagline'] = 'La Enciclopedia de la Universidad del Bío-Bío';
$conf['license'] = 'gnufdl';
$conf['recent'] = 25;
$conf['recent_days'] = 14;
$conf['youarehere'] = 1;
$conf['showuseras'] = 'username_link';
$conf['maxtoclevel'] = '4';
$conf['useacl'] = 1;
$conf['autopasswd'] = 0;
$conf['defaultteachergroup'] = 'docente';
$conf['defaultgroup'] = 'estudiante';
$conf['superuser'] = '@admin';
$conf['manager'] = '@mantenedor';
$conf['teacherismanager'] = 1;
$conf['disableactions'] = 'profile_delete';
$conf['htmlok'] = 1;
$conf['jpg_quality'] = 100;
$conf['subscribers'] = 1;
$conf['mailfrom'] = 'crialvea@alumnos.ubiobio.cl';
$conf['userewrite'] = '2';
$conf['useslash'] = 1;
$conf['canonical'] = 1;
$conf['plugin']['avatar']['namespace'] = 'user:gravatar';
$conf['plugin']['captcha']['question'] = '¿Cuál es la respuesta a la vida, el universo y todo?';
$conf['plugin']['codemirror']['nativeeditor'] = 1;
$conf['plugin']['codemirror']['codesyntax'] = 1;
$conf['plugin']['davcal']['hide_settings'] = 1;
$conf['plugin']['davcal']['monday'] = 1;
$conf['plugin']['davcal']['timeformat'] = '24h';
$conf['plugin']['davcal']['weeknumbers'] = 1;
$conf['plugin']['discussion']['automatic'] = 1;
$conf['plugin']['discussion']['excluded_ns'] = '/(playground|wiki)/';
$conf['plugin']['discussion']['allowguests'] = 0;
$conf['plugin']['discussion']['showguests'] = 0;
$conf['plugin']['discussion']['linkemail'] = 1;
$conf['plugin']['discussion']['visibilityButton'] = 1;
$conf['plugin']['emoji']['assetsrc'] = 'builtin';
$conf['plugin']['fastwiki']['fastpages'] = 0;
$conf['plugin']['fastwiki']['save'] = 1;
$conf['plugin']['gallery']['options'] = 'cache,crop,lightbox,reverse,showname,showtitle';
$conf['plugin']['howhard']['confhowhardstyle'] = '2';
$conf['plugin']['howhard']['confhowhardcompact'] = 1;
$conf['plugin']['icons']['defaultSize'] = '24';
$conf['plugin']['icons']['fontAwesomeURL'] = 'lib/tpl/bootstrap3/assets/font-awesome/css/font-awesome.min.css';
$conf['plugin']['mathjax']['config'] = 'MathJax.Hub.Config({
    tex2jax: {
        inlineMath: [ ["$","$"], ["\\\\(","\\\\)"] ],
        displayMath: [ ["$$","$$"], ["\\\\[","\\\\]"] ],
        processEscapes: true
    }
});';
$conf['plugin']['pagelist']['showheader'] = 1;
$conf['plugin']['pagelist']['showcomments'] = 1;
$conf['plugin']['pagelist']['showtags'] = 1;
$conf['plugin']['passpolicy']['minlen'] = 4;
$conf['plugin']['passpolicy']['pools'] = 'lower,upper,numeric';
$conf['plugin']['passpolicy']['minpools'] = 0;
$conf['plugin']['passpolicy']['user'] = 0;
$conf['plugin']['passpolicy']['nocommon'] = 0;
$conf['plugin']['passpolicy']['autobits'] = 24;
$conf['plugin']['preregister']['captcha'] = 'ninguno';
$conf['plugin']['rater']['voting_restriction'] = 1;
$conf['plugin']['showpageafterlogin']['page_after_login'] = 'bienvenido';
$conf['plugin']['showpageafterlogin']['login_display_count'] = 5;
$conf['plugin']['smtp']['smtp_host'] = 'smtp.gmail.com';
$conf['plugin']['smtp']['smtp_port'] = 587;
$conf['plugin']['smtp']['smtp_ssl'] = 'tls';
$conf['plugin']['smtp']['auth_user'] = 'crialvea@alumnos.ubiobio.cl';
$conf['plugin']['smtp']['auth_pass'] = 'CrawiS93-60259518';
$conf['plugin']['userhomepage']['create_private_ns'] = 1;
$conf['plugin']['userhomepage']['use_start_page'] = 0;
$conf['plugin']['userhomepage']['create_public_page'] = 1;
$conf['plugin']['userhomepage']['acl_all_public'] = 'noacl';
$conf['plugin']['userhomepage']['templates_path'] = '../lib/plugins/userhomepage';
$conf['plugin']['userhomepage']['acl_all_templates'] = 'noacl';
$conf['plugin']['userhomepage']['acl_user_templates'] = 'noacl';
$conf['plugin']['userhomepage']['redirection'] = 0;
$conf['plugin']['userhomepage']['userlink_fa'] = 1;
$conf['tpl']['bootstrap3']['bootstrapTheme'] = 'bootswatch';
$conf['tpl']['bootstrap3']['bootswatchTheme'] = 'flatly';
$conf['tpl']['bootstrap3']['showTools'] = 'logged';
$conf['tpl']['bootstrap3']['individualTools'] = 1;
$conf['tpl']['bootstrap3']['showIndividualTool'] = 'site,page';
$conf['tpl']['bootstrap3']['showSearchForm'] = 'logged';
$conf['tpl']['bootstrap3']['showAdminMenu'] = 1;
$conf['tpl']['bootstrap3']['semantic'] = 1;
$conf['tpl']['bootstrap3']['fluidContainerBtn'] = 1;
$conf['tpl']['bootstrap3']['tableStyle'] = 'striped,hover,condensed,responsive';
$conf['tpl']['bootstrap3']['showPageTools'] = 'logged';
$conf['tpl']['bootstrap3']['useGravatar'] = 1;
$conf['tpl']['bootstrap3']['showDiscussion'] = 1;
$conf['tpl']['bootstrap3']['discussionPage'] = 'discusion:@ID@';
$conf['tpl']['bootstrap3']['showCookieLawBanner'] = 1;
$conf['tpl']['bootstrap3']['googleAnalyticsNoTrackUsers'] = 1;
$conf['tpl']['bootstrap3']['pageInfoDateFormat'] = 'human';
$conf['tpl']['bootstrap3']['showPageIcons'] = 1;
$conf['tpl']['bootstrap3']['collapsibleSections'] = 1;
$conf['updatecheck'] = '0';
$conf['plugin']['iframe']['js_ok'] = '1';
$conf['plugin']['emphasis']['colors'] = '#F44336, #4CAF50, #F57C00, #E91E63, #FFA000';
$conf['plugin']['emphasis']['background-colors'] = '#F44336, #4CAF50, #F57C00, #E91E63, #FFA000';
$conf['plugin']['linkback']['allow_guests'] = '1';
$conf['plugin']['linkback']['ping_internal'] = '1';
$conf['plugin']['linkback']['show_trackback_url'] = '1';
$conf['plugin']['linkback']['log_processing'] = '1';
$conf['plugin']['linkback']['usefavicon'] = '1';
$conf['plugin']['linkback']['antispam_linkcount_enable'] = '1';
$conf['plugin']['linkback']['antispam_linkcount_moderate'] = '1';
$conf['plugin']['linkback']['antispam_wordblock_enable'] = '1';
$conf['plugin']['linkback']['antispam_wordblock_moderate'] = '1';
$conf['plugin']['linkback']['antispam_host_enable'] = '1';
$conf['plugin']['linkback']['antispam_host_moderate'] = '1';
$conf['plugin']['linkback']['antispam_link_enable'] = '1';
$conf['plugin']['linkback']['antispam_link_moderate'] = '1';

// end auto-generated content
